language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"

install:
 - pip install -e .[commands,consumers]
 - pip install nose
script: python setup.py nosetests
notifications:
    email: false
    irc:
        - "irc.freenode.net#fedora-apps"
    on_success: change
    on_failure: change

matrix:
  allow_failures:
    - python: "3.3"
    - python: "3.4"
